name: ci

on:
  push:
    branches:
      - docker

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Forge Hub
        uses: docker/login-action@v3
        with:
          registry: forge.k3s.fr
          username: ${{ secrets.FORGEHUB_USERNAME }}
          password: ${{ secrets.FORGEHUB_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: forge.k3s.fr/frank/opentsdb-auth-proxy:latest

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: frankkkkk/opentsdb-auth-proxy:latest